### ISSUE TITLE
Why are you using legacy (i.e. non descriptor) wallets for this project?

### ISSUE THREAD

**Issue by michaelfolkson** [1440000bytes/p2p#1]
Why are you using legacy (i.e. non descriptor) wallets for this?

You said "everything doesn't work with descriptor wallets" on the Core issue. What in particular doesn't work with descriptor wallets that makes you want to use legacy wallets for this? You can obviously use whatever you want but curious.

(This has nothing to do with the timeline for the Core wallet btw. An independent wallet can do whatever it wants and isn't impacted by what the Core wallet does or doesn't do.)

**Comment by 1440000bytes** [comment]
> Why are you using legacy (i.e. non descriptor) wallets for this?

Because I get this error when trying to import multisig in a descriptor wallet as watch only:

```
Only legacy wallets are supported by this command (code -4)
```

It is not possible for users (buyer and seller) to sign transactions without importing. Related experiment: https://bitcoin.stackexchange.com/a/115246

> This has nothing to do with the timeline for the Core wallet btw. An independent wallet can do whatever it wants and isn't impacted by what the Core wallet does or doesn't do.

This is related o core wallet because we will use core wallet and JSON-RPC. Its not an independent wallet.

**Comment by michaelfolkson** [comment]
> Because I get this error when trying to import multisig in a descriptor wallet as watch only:

Can't you use `importmulti` RPC? That supports descriptors and watch only?

> This is related to core wallet because we will use core wallet and JSON-RPC. Its not an independent wallet.

If users (e.g. independent wallets) are using a Core **RPC** then that impacts the decision on whether to ultimately deprecate that RPC in Core. I'm not clear why what the Core **wallet** does impacts independent wallets. A wallet can use Core RPCs without replicating Core wallet functionality.

**Comment by 1440000bytes** [comment]
> Can't you use importmulti RPC? That supports descriptors and watch only?

I am using `importmulti` RPC

**Comment by michaelfolkson** [comment]
The `importmulti` "watchonly" [argument](https://bitcoincore.org/en/doc/0.17.0/rpc/wallet/importmulti/) throws an error for descriptor wallets? Is that right?

**Comment by michaelfolkson** [comment]
Unless you have already asked about this somewhere probably worth asking why on StackExchange etc?

**Comment by 1440000bytes** [comment]
> Unless you have already asked about this somewhere probably worth asking why on StackExchange etc?

Will do because this project is important for me

**Comment by michaelfolkson** [comment]
Not interested in engaging with you. Any time I or anyone else tries to direct you from trampling on Core PRs, issues with questions, comments that are diverging from the point of those PRs, issues you ignore them and respond sarcastically. So yeah closing this and good luck getting people to work with you.
